### ISSUE TITLE
Adjusted p-values and predictions should be computed outside the for loop 

### ISSUE THREAD

**Issue by jccaicedo** [anbrooks/eVIP#2]
https://github.com/anbrooks/eVIP/blob/e0531b4c399b4a70922174cd453fcfd0499a962c/eVIP_predict.py#L346-L392

Make one indentation back.

**Comment by althornt** [comment]
Thanks. This was corrected in the new version of eVIP. 
Note: This code is now part of the eVIP_compare.py script.
